### ISSUE TITLE
How to calculate Collateral Available

### ISSUE THREAD

**Issue by foonsun** [blockworks-foundation/mango-explorer#42]
Dear Team,

1、I have run the ''show-account-balances" in the /bin directory.I can see the total value of the account. How to calculate collateral available ?

2、It is confused that the member of the open orders. what is the meaning of base_token_free, quote_token_free, etc?

thanks.

```
# # 🥭 OpenOrders class
#
class OpenOrders(AddressableAccount):
    def __init__(self, account_info: AccountInfo, version: Version, program_address: PublicKey,
                 account_flags: AccountFlags, market: PublicKey, owner: PublicKey,
                 base_token_free: Decimal, base_token_total: Decimal, quote_token_free: Decimal,
                 quote_token_total: Decimal, placed_orders: typing.Sequence[PlacedOrder],
                 referrer_rebate_accrued: Decimal) -> None:
        super().__init__(account_info)
        self.version: Version = version
        self.program_address: PublicKey = program_address
        self.account_flags: AccountFlags = account_flags
        self.market: PublicKey = market
        self.owner: PublicKey = owner
        self.base_token_free: Decimal = base_token_free
        self.base_token_total: Decimal = base_token_total
        self.quote_token_free: Decimal = quote_token_free
        self.quote_token_total: Decimal = quote_token_total
        self.placed_orders: typing.Sequence[PlacedOrder] = placed_orders
        self.referrer_rebate_accrued: Decimal = referrer_rebate_accrued
```

Thanks.

**Comment by OpinionatedGeek** [comment]
Hi there,

The health and collateral calculations are a work-in-progress. If you want to try out the current state of them, you can try running `show-account-dataframe`. (It outputs a large table - a `pandas` `DataFrame` - so it might be worth redirecting this output to a file where you can turn off word-wrapping.)

As for your second question, I really do take your point, but OpenOrders is a Serum thing Mango has to deal with. It's largely out of our control, it's just the way Serum works (and that is largely dictated by running on Solana). That `OpenOrders` code is only in Mango because it wasn't well exposed in pyserum, but [here's the pyserum layout of that structure](https://github.com/serum-community/pyserum/blob/alpha/pyserum/_layouts/open_orders.py)

I'll try to explain a bit about what's going on though.

The Serum program can't transfer your tokens, only you can sign the transaction to do that. That prevents many orderbook approaches.

So what happens when you place an order is you transfer your tokens for the trade to a 'halfway house' - an account that Serum controls, but that you can get the tokens back from if the trade isn't filled. This is called the OpenOrders account.

When the trade is matched on the orderbook (possibly hours after you placed the order), Serum withdraws the tokens from your OpenOrders account and deposits the traded tokens.

At this point you usually need to 'settle' the fill to move the new tokens (and any remaining trade tokens) into your wallet.

The properties `base_token_free`, `base_token_total`, `quote_token_free`, and `quote_token_total` are there to track the native quantities of the tokens in the OpenOrders account - the 'total' properties say how many tokens this OpenOrders account holds, and the 'free' properties say how many tokens are not currently allocated to orders in that OpenOrders account.

I agree this isn't intuitive, but it's how Serum works so it's how Mango Spot has to work too.

**Comment by foonsun** [comment]
Thank you for the detailed explanation of serum open orders.It is a great help.thanks.
