### ISSUE TITLE
BUG:  Init Health,Maint Health,Levearge, Available Collateral cal error When SOL/USDC open orders exist

### ISSUE THREAD

**Issue by foonsun** [blockworks-foundation/mango-explorer#47]
Dear Team,

When placing SOL/USDC Buy 100 size Orders,the orders are open in the market.

However, the caluation of init health, maint health, leverage, available collateral are wrong.

I have fixed the error of leverage. "QuoteLocked" is needed to added to asset value.
==> leverage, total value are correct.

However, the init health,maint health and available collateral are still wrong. I have no idea that how to fix the bug.
pls help check it.

thanks.

```
def unweighted_assets(
        self, frame: pandas.DataFrame
    ) -> typing.Tuple[Decimal, Decimal]:
        non_quote = frame.loc[frame["Symbol"] != self.shared_quote_token.symbol]
        quote = frame.loc[
            frame["Symbol"] == self.shared_quote_token.symbol, "SpotValue"
        ].sum()

        assets = Decimal(0)
        liabilities = Decimal(0)
        if quote > 0:
            assets = quote
        else:
            liabilities = quote

        liabilities += (
            Account.__sum_neg(non_quote, "SpotValue") + non_quote["PerpLiability"].sum()
        )

        assets += (
            Account.__sum_pos(non_quote, "SpotValue")
            + non_quote["PerpAsset"].sum()
            + Account.__sum_pos(non_quote, "QuoteUnsettled")
            + Account.__sum_pos(non_quote, "QuoteLocked")
        )

        return assets, liabilities

```

**Comment by OpinionatedGeek** [comment]
Hi,

Thanks for reporting this.

The valuations have been a Work In Progress for a while, and have a few issues. That's why, for instance, some commands say '⚠ WARNING! ⚠ This is a work-in-progress and these figures may be wrong!'

I have been working on this lately though, and I have some changes that should mean the figures are complete and accurate and I'll be removing that warning (and some stale code).

One thing that really helps, if the situation comes up again - taking a complete snapshot of the account for unit tests. If there's a problem/bug, having a unit test for that case makes it easier to fix and also ensures the bug doesn't come back. If you look at the `regenerate` command in any of the `tests/testdata/accountX` directories you'll see examples, but really what's needed is a snapshot of the `Group`, `Cache`, `Account`, and every Spot `OpenOrders` account belonging to the Mango Account. Even if you don't want to tackle the test or fix yourself, a demonstration of the problem is valuable.

I'll let you know when the new code is pushed to this repo.

**Comment by foonsun** [comment]
thanks anyway.Waiting.
