### ISSUE TITLE
Bug: Perp Position Value is not correct.

### ISSUE THREAD

**Issue by foonsun** [blockworks-foundation/mango-explorer#51]
Dear Team,

I have updated the latest mango-explorer version, however, my perp positions are not correct.eg: my BTC-PERP is 0.087,but the value of mango is 87,800. SOL-PERP has the same issue.

pls help check it.

The log is below after running "./bin/show-accounts"

```
« AccountSlot [1] BTC
            Net Value:     « InstrumentValue:         0.00000000 BTC »
                Deposited: « InstrumentValue:         0.00000000 BTC » (raw value: 0E-20)
                Borrowed:  « InstrumentValue:         0.00000000 BTC » (raw value 0E-20)
            Spot OpenOrders: None
            Perp Account:
                « PerpAccount
                    Base Position: « InstrumentValue:    87,800.00000000 BTC »
                    Quote Position: -3783574498.53515607565438472193
                    Long Settled Funding: 587094.74736902058174692343
                    Short Settled Funding: 585522.72434996363400827590
                    Bids Quantity: 0
                    Asks Quantity: 0
                    Taker Base: 0
                    Taker Quote: 0
                    MNGO Accrued: « InstrumentValue:         0.45457900 MNGO »
                    OpenOrders:
                        « PerpOpenOrders
                            Orders:
                                None
                        »
                »
```

**Comment by OpinionatedGeek** [comment]
The value stored (and shown) in the PerpAccount is - confusingly - in 'lot sizes' rather than in the quote currency.

The value shown in the PerpPositionSize column in the `DataFrame` should be correctly adjusted to the quote currency - check out the example of [loading the `Account `data into a `DataFrame`](https://github.com/blockworks-foundation/mango-explorer-examples/blob/main/ShowAccountDataFrame.ipynb).

**Comment by foonsun** [comment]
Thanks.I have used the account frame.It's great!
