### ISSUE TITLE
show-account-balances and show-account-valuation return an error

### ISSUE THREAD

**Issue by 5QgKxT2j** [blockworks-foundation/mango-explorer#9]
When I run show-account-balances and show-account-valuation, I get the following error.
What parameters should be specified?

Command: ./bin/show-account-valuation --address <My Wallet Address>

Traceback (most recent call last):
  File "/app/./bin/show-account-valuation", line 34, in <module>
    valuation: mango.Valuation = mango.Valuation.from_wallet(context, group, cache, address)
  File "/app/mango/valuation.py", line 166, in from_wallet
    spl_tokens = TokenValuation.all_from_wallet(context, group, cache, address)
  File "/app/mango/valuation.py", line 67, in all_from_wallet
    balances = group.fetch_balances(context, address)
  File "/app/mango/group.py", line 306, in fetch_balances
    balance = TokenValue.fetch_total_value(context, root_address, basket_token.token)
  File "/app/mango/tokenvalue.py", line 64, in fetch_total_value
    value = TokenValue.fetch_total_value_or_none(context, account_public_key, token)
  File "/app/mango/tokenvalue.py", line 51, in fetch_total_value_or_none
    token_accounts = context.client.get_token_accounts_by_owner(account_public_key, opts)
  File "/app/mango/client.py", line 604, in get_token_accounts_by_owner
    response = self.compatible_client.get_token_accounts_by_owner(owner, token_account_options, commitment)
  File "/app/mango/client.py", line 360, in get_token_accounts_by_owner
    return self._send_request("getTokenAccountsByOwner", str(owner), account_options, options)
  File "/app/mango/client.py", line 451, in _send_request
    raise TransactionException(transaction, exception_message, error_code, self.name, self.cluster_url,
mango.client.TransactionException: « 𝚃𝚛𝚊𝚗𝚜𝚊𝚌𝚝𝚒𝚘𝚗𝙴𝚡𝚌𝚎𝚙𝚝𝚒𝚘𝚗 in 'Mango Explorer' [getTokenAccountsByOwner]: -32602:: Transaction failed with: 'Invalid param: could not find mint'
    Accounts:
        No accounts
    Errors:
        No error text returned
    Logs:
        No logs

**Comment by OpinionatedGeek** [comment]
Hi,

Thanks for reporting this.

The good news: you're not doing anything wrong. It's a bug.

`show-account-valuation` is very much a Work In Progress and if I were you I wouldn't trust its figures - they can sometimes be very wrong.

This particular problem though is a result of some changes made for the ADA perp market.

ADA is unique among the Mango markets in that it has no underlying spot market. There is no ADA token on Solana (although you might be able to bridge them somehow), so there's no Serum spot market.

Some bits of `mango-explorer` were written with the assumption that for a market there'd be a base token and a quote token. That was true, up until ADA. Now... now those assumptions need to be fixed in the code. I'm in the process of doing this, and after editing over 100 code files I'm nearly done.

The code now has the notion of an `Instrument` (which has a symbol, name, number of decimal places) and a `Token` (which derives from `Instrument` and has all the same properties) which adds a `mint` public key and represents an SPL token. Some operations require `Token`s, some only require `Instrument`s, and sorting that out took longer than expected. Sorry.

The new version to fix this should be available soon.

**Comment by 5QgKxT2j** [comment]
Thank you for your hard work!

As you said, ADA causes the error and I can see my account valudation by skipping the fetch function when token symbol is ADA, as a workaround.
I'm looking forward to the new code you've been writing now.

Thanks
